const FETCH_MOVIE_START = 'FETCH_MOVIE_START';
const FETCH_MOVIE_SUCCES = 'FETCH_MOVIE_SUCCES';
const FETCH_MOVIE_ERROR = 'FETCH_MOVIE_ERROR';

const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const CHANGE_STEP = 'CHANGE_STEP';

export {
  FETCH_MOVIE_START,
  FETCH_MOVIE_SUCCES,
  FETCH_MOVIE_ERROR,
  INCREMENT,
  DECREMENT,
  CHANGE_STEP,
};
